# Generated by Django 5.2.7 on 2026-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('adventure', 'adventure'), ('street', 'street'), ('long trip', 'long trip')], max_length=244)),
                ('pricePerRide', models.IntegerField(default=150)),
                ('currency', models.CharField(choices=[('IND', 'IND'), ('USD', 'USD')], default='IND', max_length=10)),
                ('maxOccupancy', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
