# Generated by Django 5.2.7 on 2026-01-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_bikeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupiedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupied_dates', to='ride.bike')),
            ],
        ),
    ]
