# Generated by Django 5.2.7 on 2026-02-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupieddate',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupied_dates', to='ride.booking'),
        ),
    ]
